const profileSkills = [
  { value: '3DPrinting', label: '3D Printing' },
  { value: 'Art', label: 'Art' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Beekeeping', label: 'Beekeeping' },
  { value: 'CandleMaking', label: 'Candle Making' },
  { value: 'Coding', label: 'Coding' },
  { value: 'Cosplay', label: 'Cosplay' },
  { value: 'Crafts', label: 'Crafts' },
  { value: 'Crochet', label: 'Crochet' },
  { value: 'DIYBeautyAndSkincare', label: 'DIY Beauty And Skincare' },
  { value: 'DIYEducationalToys', label: 'DIY Educational Toys' },
  { value: 'DIYElectronicsKits', label: 'DIY Electronics Kits' },
  { value: 'DIYFurniture', label: 'DIY Furniture' },
  { value: 'DIYGiftsAndHandmadeCards', label: 'DIY Gifts And Handmade Cards' },
  { value: 'DIYHomeDecor', label: 'DIY Home Decor' },
  { value: 'Electronics', label: 'Electronics' },
  { value: 'Fashion', label: 'Fashion' },
  { value: 'Food', label: 'Food' },
  { value: 'GameDevelopment', label: 'Game Development' },
  { value: 'Gardening', label: 'Gardening' },
  { value: 'GraphicDesign', label: 'Graphic Design' },
  { value: 'HomeImprovement', label: 'Home Improvement' },
  { value: 'Jewelry', label: 'Jewelry' },
  { value: 'Knitting', label: 'Knitting' },
  { value: 'Leatherworking', label: 'Leatherworking' },
  { value: 'Metalworking', label: 'Metalworking' },
  { value: 'ModelBuilding', label: 'ModelBuilding' },
  { value: 'Music', label: 'Music' },
  { value: 'Other', label: 'Other' },
  { value: 'Painting', label: 'Painting' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Pottery', label: 'Pottery' },
  { value: 'Quilting', label: 'Quilting' },
  { value: 'Robotics', label: 'Robotics' },
  { value: 'Sculpture', label: 'Sculpture' },
  { value: 'Sewing', label: 'Sewing' },
  { value: 'Soapmaking', label: 'Soapmaking' },
  { value: 'Taxidermy', label: 'Taxidermy' },
  { value: 'Upcycling', label: 'Upcycling' },
  { value: 'VideoProduction', label: 'Video Production' },
  { value: 'Weaving', label: 'Weaving' },
  { value: 'Woodworking', label: 'Woodworking' },
];

export default profileSkills;
